# Generated by Django 5.2.1 on 2025-06-03 17:23

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('courier', 'Курьер')], max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Номер машины')),
                ('tech_passport_front', models.ImageField(upload_to=users.models.car_tech_passport_front_path, verbose_name='Техпаспорт (лицевая)')),
                ('tech_passport_back', models.ImageField(upload_to=users.models.car_tech_passport_back_path, verbose_name='Техпаспорт (обратная)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Профиль Клиента',
                'verbose_name_plural': 'Профили Клиентов',
            },
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='courier_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('id_card_front', models.ImageField(upload_to=users.models.courier_id_card_front_path, verbose_name='Уд. личности (лицевая)')),
                ('id_card_back', models.ImageField(upload_to=users.models.courier_id_card_back_path, verbose_name='Уд. личности (обратная)')),
                ('driver_license_front', models.ImageField(upload_to=users.models.courier_driver_license_front_path, verbose_name='Вод. удостоверение (лицевая)')),
                ('driver_license_back', models.ImageField(upload_to=users.models.courier_driver_license_back_path, verbose_name='Вод. удостоверение (обратная)')),
                ('selfie_with_id', models.ImageField(upload_to=users.models.courier_selfie_with_id_path, verbose_name='Селфи с уд. личности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.car', verbose_name='Автомобиль')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Профиль Курьера',
                'verbose_name_plural': 'Профили Курьеров',
            },
        ),
    ]
