services:
  db:
    image: postgres:15-alpine
    container_name: jibekjoly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    expose:
      - 5432
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: jibekjoly_redis
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jibekjoly_app
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: jibekjoly_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: jibekjoly_certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_conf:
  certbot_www: