# Generated by Django 5.2.1 on 2025-06-03 17:23

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='Адрес забора')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('pickup_date', models.DateField(verbose_name='Желаемая дата забора')),
                ('pickup_time_slot', models.CharField(max_length=100, verbose_name='Желаемый временной промежуток забора')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Имя получателя')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Номер телефона получателя')),
                ('sender_name_snapshot', models.CharField(max_length=255, verbose_name='ФИО отправителя (на момент заказа)')),
                ('sender_phone_snapshot', models.CharField(max_length=20, verbose_name='Телефон отправителя (на момент заказа)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('unique_order_id', models.CharField(default=orders.models.generate_unique_order_id, editable=False, max_length=12, unique=True, verbose_name='Уникальный ID заказа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена доставки')),
                ('pickup_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время фактического забора заказа')),
                ('delivery_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время фактической доставки заказа')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'ordering': ['order_index', 'name'],
            },
        ),
    ]
