# Generated by Django 5.2.1 on 2025-06-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_client', to='users.clientprofile', verbose_name='Клиент (Отправитель)'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_courier', to='users.courierprofile', verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_orders', to='core.city', verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_orders', to='core.city', verbose_name='Город отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='package_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.packagesize', verbose_name='Размер заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus', verbose_name='Статус заказа'),
        ),
    ]
